spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Piotr1992/configuration.git
          username: szyperek.piotr@o2.pl
          password: PLSzW-2020
          clone-on-start: true
          default-label: master
          refresh-rate: 15
          timeout: 5
          search-paths: 'configuration/,configuration/{application}/{profile}'
server:
  port: 8888